name:                typelevel-experiment
version:             0.1.0.0
github:              "githubuser/typelevel-experiment"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/typelevel-experiment#readme>

dependencies:
- base >= 4.7 && < 5
- text
- singletons


default-extensions:
- DataKinds
- DefaultSignatures
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- KindSignatures
- NoCUSKs
- NoStarIsType
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneKindSignatures
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

library:
  source-dirs: src

executables:
  typelevel-experiment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typelevel-experiment

tests:
  typelevel-experiment-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typelevel-experiment
